-- Thêm cột SOLUONG vào bảng HANG_HOA
ALTER TABLE `hang_hoa` ADD COLUMN `SOLUONG` INT NOT NULL DEFAULT 0;

-- Tạo bảng KHO
CREATE TABLE `kho` (
    `ID_KHO` INT NOT NULL AUTO_INCREMENT,
    `ID_HANGHOA` INT NOT NULL,
    `ID_CTMUA` INT DEFAULT NULL,
    `ID_CTBAN` INT DEFAULT NULL,
    `SOLUONG` INT NOT NULL,
    `LOAI_CHUNG_TU` VARCHAR(50) NOT NULL COMMENT 'MUA hoặc BAN',
    `NGAY_TAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID_KHO`),
    FOREIGN KEY (`ID_HANGHOA`) REFERENCES `hang_hoa`(`ID_HANGHOA`) ON DELETE CASCADE
);
