<?php
require_once ROOT . '/config/Database.php';
require_once ROOT . '/models/HangHoa.php';
class CartController {
    private $db;
    private $hangHoaModel;
    public function __construct($db) {
        $this->db = $db;
        $this->hangHoaModel = new HangHoa($db);
        if(!isset($_SESSION)) session_start();
        if(!isset($_SESSION['cart'])) $_SESSION['cart'] = [];
    }

    public function index() {
        $total = $this->recalcCart();
        $cart = $_SESSION['cart'];
        include ROOT . '/views/client/cart/index.php';
    }

    public function checkout() {
        // Accept either legacy `$_SESSION['user']` or `$_SESSION['user_id']` set by UserController
        if (!isset($_SESSION['user']) && !isset($_SESSION['user_id'])) {
            header("Location: index.php?controller=user&action=login");
            exit;
        }
        $cart = $_SESSION['cart'] ?? [];
        $total = $this->recalcCart();
        if (empty($cart)) {
            header("Location: index.php?controller=cart&action=index");
            exit;
        }

        // If form posted, place order
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            require_once ROOT . '/models/ChungTuBan.php';
            require_once ROOT . '/models/ChungTuBanCT.php';

            $orderModel = new ChungTuBan($this->db);
            $orderDetailModel = new ChungTuBanCT($this->db);

            $masoct = 'CTB-' . time();
            $ngaydathang = date('Y-m-d H:i:s');
            // support both session formats
            $id_khachhang = $_SESSION['user_id'] ?? ($_SESSION['user']['ID_KHACHHANG'] ?? null);
            $tongtien = $_SESSION['cart_total'] ?? $total;

            try {
                $this->db->beginTransaction();

                $orderId = $orderModel->create([
                    'MASOCT' => $masoct,
                    'NGAYDATHANG' => $ngaydathang,
                    'ID_KHACHHANG' => $id_khachhang,
                    'TONGTIENHANG' => $tongtien,
                    'THUE' => 0,
                    'TRANGTHAI' => 1,
                    'GHICHU' => ''
                ]);

                if (!$orderId) {
                    throw new Exception('Tạo đơn hàng thất bại (orderId null).');
                }

                foreach ($cart as $item) {
                    $giaban = isset($item['price']) ? (float)$item['price'] : 0;
                    $soluong = isset($item['quantity']) ? (int)$item['quantity'] : 0;
                    // THANHTIEN is generated by the DB (GIABAN * SOLUONG), so don't insert it explicitly
                    $orderDetailModel->create([
                        'ID_CTBAN' => $orderId,
                        'ID_HANGHOA' => $item['id'],
                        'GIABAN' => $giaban,
                        'SOLUONG' => $soluong
                    ]);
                }

                $this->db->commit();

                // Clear cart
                unset($_SESSION['cart']);
                unset($_SESSION['cart_total']);
                header('Location: index.php?controller=user&action=orders');
                exit;
            } catch (Exception $e) {
                // Roll back and show error
                if ($this->db->inTransaction()) $this->db->rollBack();
                $error = 'Lỗi lưu đơn hàng: ' . $e->getMessage();
                include ROOT . "/views/client/cart/checkout.php";
                return;
            }
        }

        include ROOT . "/views/client/cart/checkout.php";
    }

    // public function placeOrder() {
    //     if (!isset($_SESSION['user'])) {
    //         header("Location: index.php?controller=user&action=login");
    //         exit;
    //     }
    //     $cart = $_SESSION['cart'] ?? [];
    //     if (empty($cart)) {
    //         header("Location: index.php?controller=cart&action=index");
    //         exit;
    //     }
    //     // MODELS
    //     $orderModel = new ChungTuBan($GLOBALS['db']);
    //     $orderDetailModel = new ChungTuBanCT($GLOBALS['db']);
    //     // 1. Tạo đơn
    //     $orderId = $orderModel->create([
    //         "ID_KHACHHANG" => $_SESSION['user']['ID_KHACHHANG'],
    //         "NGAYLAP" => date("Y-m-d H:i:s"),
    //         "TONGTIEN" => $_POST["total"]
    //     ]);
    //     // 2. Tạo chi tiết đơn
    //     foreach ($cart as $item) {
    //         $orderDetailModel->create([
    //             "ID_CHUNGTUBAN" => $orderId,
    //             "ID_HANGHOA" => $item["ID_HANGHOA"],
    //             "SOLUONG" => $item["SOLUONG"],
    //             "DONGIA" => $item["DONGIA"]
    //         ]);
    //     }
    //     // 3. Xóa giỏ hàng
    //     unset($_SESSION["cart"]);
    //     // 4. Chuyển qua trang xem đơn
    //     header("Location: index.php?controller=user&action=orders");
    //     exit;
    // }

    public function add() {
        if (!isset($_GET['id'])) {
            die("Không có ID sản phẩm");
        }

        $id = (int)$_GET['id'];

        if (!isset($_SESSION['cart'])) {
            $_SESSION['cart'] = [];
        }

        if (isset($_SESSION['cart'][$id])) {
            $_SESSION['cart'][$id]['quantity'] += 1;
        } else {

            // Use client-aware getter so price (DONGIA) from DON_GIA_BAN is included
            if (method_exists($this->hangHoaModel, 'getByIdClient')) {
                $product = $this->hangHoaModel->getByIdClient($id);
            } else {
                $product = $this->hangHoaModel->getById($id);
            }

            if (!$product) {
                die("Sản phẩm không tồn tại");
            }

            $_SESSION['cart'][$id] = [
                'id'       => $product['ID_HANGHOA'],
                'name'     => $product['TENHANGHOA'],
                'price'    => $product['DONGIA'] ?? 0,
                'image'    => $product['HINHANH'] ?? '',
                'quantity' => 1
            ];
        }

        $this->recalcCart();

        header("Location: index.php?controller=cart&action=index");
        exit;
    }

    private function recalcCart() {
        if (!isset($_SESSION['cart']) || !is_array($_SESSION['cart'])) {
            $_SESSION['cart'] = [];
            $_SESSION['cart_total'] = 0;
            return 0;
        }

        $total = 0;
        foreach ($_SESSION['cart'] as $key => &$item) {
            $price = isset($item['price']) ? (float)$item['price'] : 0;
            $qty = isset($item['quantity']) ? (int)$item['quantity'] : 0;
            if ($qty < 0) $qty = 0;
            $item['price'] = $price;
            $item['quantity'] = $qty;
            $item['subtotal'] = $price * $qty;
            $total += $item['subtotal'];
        }
        unset($item);

        $_SESSION['cart_total'] = $total;
        return $total;
    }

    public function remove() {
        if (!isset($_GET['id'])) {
            header("Location: index.php?controller=cart&action=index");
            exit;
        }
        $id = (int)$_GET['id'];
        if (isset($_SESSION['cart'][$id])) {
            unset($_SESSION['cart'][$id]);
            $this->recalcCart();
        }
        header("Location: index.php?controller=cart&action=index");
        exit;
    }

    public function update() {
        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            header("Location: index.php?controller=cart&action=index");
            exit;
        }
        $id = isset($_POST['id']) ? (int)$_POST['id'] : 0;
        $qty = isset($_POST['quantity']) ? (int)$_POST['quantity'] : 1;
        if ($id && isset($_SESSION['cart'][$id])) {
            $_SESSION['cart'][$id]['quantity'] = max(1, $qty);
            $this->recalcCart();
        }
        header("Location: index.php?controller=cart&action=index");
        exit;
    }

}
